sample: ["Int-01_S42_L005", "Int-02_S43_L005"]

rg: ["INT_1","INT_2"]


# , "INT_3", "INT_4", "LIV_1", "LIV_2", "LIV_3", LIV_4"]

# Rest of samples
# , "Int-03_S44_L005", "Int-04_S45_L005", "Liv-01_S38_L005", "Liv-02_S39_L005", "Liv-03_S40_L005", "Liv-04_S41_L005"]